# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='storage_system.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='storage_system.Status', verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('0', '未入库'), ('1', '已入库'), ('2', '需补货'), ('3', '已出售')], max_length=32, verbose_name='状态'),
        ),
    ]
