# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='payment_method',
            field=models.CharField(default='微信支付', max_length=200, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='顾客生日,格式:1999-01-01'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='image',
            field=models.ImageField(default='media/product/default.png', upload_to='media/product', verbose_name='商品图片'),
        ),
    ]
