# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-27 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_info',
            field=models.TextField(blank=True, null=True, verbose_name='顾客信息'),
        ),
    ]
