# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_system', '0002_auto_20191225_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='顾客生日,格式:1999-01-01'),
        ),
    ]
